book_begin = r"""\documentclass[twoside,makeidx]{book}

%%%%%%%%%%%%%%%%%%%%
% WARNING: This file was generated automatically. It is likely that
% you will eventually have to modify it by hand, e.g. to add abstracts
% for invited speakers or other papers that were not in the ACLPUB db
% file. However, if you re-generate this file, you will overwrite any
% manual changes you have made. So do not start making manual edits
% until you are certain that everything has been generated correctly.
%%%%%%%%%%%%%%%%%%%%

\input{preamble} 

\begin{document}

\frontmatter
\input{frontmatter}
\tableofcontents

\mainmatter
"""

day_heading_format = r"""\dayheading{{{title}}}
""".format

schedule_format = r"""\schedule{{
{items}}}
""".format

schedule_session_format = r"""\schedulesession{{{start}}}{{{end}}}{{{title}}}{{{location}}}
""".format

schedule_parallel_session_format = r"""\scheduleparallelsession{{{start}}}{{{end}}}{{{items}}}
""".format

schedule_parallel_session_item_format = r"""\scheduleparallelsessionitem{{{title}}}{{{location}}}
""".format

session_abstracts_format = r"""\sessionabstracts{{{title}}}{{{location}}}{{{chair}}}{{
{abstracts}}}
""".format

session_abstract_format = r"""\sessionabstract{{{day}}}{{{start}}}{{{end}}}{{{location}}}{{{title}}}{{{authors}}}{{{abstract}}}
""".format

session_abstract_separator = r"""\sessionabstractsep
"""

book_end = """\end{document}
"""
